version: '3'

volumes:
  vendor-store:
  node_modules-store:

services:
  php:
    container_name: app_php
    build: ./docker/php
    volumes:
    - ./live-record:/var/www/html
    # - vendor-store:/var/www/laravel/vendor
    # - node_modules-store:/var/www/laravel/node_modules
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx
    container_name: app_nginx
    ports:
    - 82:80
    volumes:
    - ./live-record:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LiveRecord
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
