version: '3'

volumes:
  vendor-store:
  node_modules-store:

services:
  php:
    container_name: app_php
    build: ./docker/php
    volumes:
    - ./live-record:/var/www/html

  nginx:
    image: nginx
    container_name: app_nginx
    ports:
    - 80:80
    volumes:
    - ./live-record:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_DATABASE: LiveRecord
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: 'Asia/Tokyo'
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306
